trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: sfpwowerscript-installsfdx-task@5
  displayName: Install SFDX
- task: sfpwowerscript-authenticateorg-task@7
  displayName: Authenticate with Salesforce
  inputs:
    method: JWT
    jwt_key_file: server.key
    username: $(SalesforceUsername)
    alias: MyScratchOrg
    isdevhub: true
    clientid: $(SalesforceClientId)
    isTelemetryEnabled: true
