trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: sfpwowerscript-installsfdx-task@5
  displayName: Install SFDX

- task: sfpwowerscript-authenticateorg-task@7
  displayName: Authenticate with DevHub
  inputs:
    method: JWT
    jwt_key_file: server.key
    username: $(SalesforceUsername)
    alias: DevHub
    isdevhub: true
    clientid: $(SalesforceClientId)
    isTelemetryEnabled: true

- task: sfpwowerscript-authenticateorg-task@7
  displayName: Authenticate with ScratchOrg
  inputs:
    method: JWT
    jwt_key_file: server.key
    username: $(ScratchOrgUsername)
    alias: MyScratchOrg
    isdevhub: false
    clientid: $(SalesforceClientId)
    isTelemetryEnabled: true

- task: sfpowerscript-deploysourcetoorg-task@6
  displayName: Deploy source to scratch org
  inputs:
    target_org: MyScratchOrg
    source_directory: 'src/force-app'
    checkonly: false
    wait_time: '20'
    testlevel: 'NoTestRun'
    isTelemetryEnabled: true
